### DISCUSSION TITLE
Kubernetes 使用方式

### DISCUSSION THREAD

**Discussion by yangkghjh** [ZingLix/immich-geodata-cn#9] [交流]
```
server:
  initContainers:
    init-geodata:
      name: init-geodata
      image: ubuntu:22.04
      imagePullPolicy: IfNotPresent
      command: ["/bin/sh", "-c"]
      args:
        - |
          apt-get update && apt-get install -y curl git zip
          cd /build/geodata
          curl -o update.sh https://raw.githubusercontent.com/ZingLix/immich-geodata-cn/refs/heads/main/geodata/update.sh
          chmod +x update.sh
          bash update.sh geodata_admin_2

          cd /tmp
          git clone https://github.com/ZingLix/immich-geodata-cn.git
          cp -r immich-geodata-cn/i18n-iso-countries/langs/* /usr/src/app/node_modules/i18n-iso-countries/langs/
      volumeMounts:
        - name: geodata
          mountPath: /build/geodata
        - name: langs
          mountPath: /usr/src/app/node_modules/i18n-iso-countries/langs
  persistence:
    geodata:
      enabled: true
      size: 1Gi
      type: emptyDir
      mountPath: /build/geodata
    langs:
      enabled: true
      size: 100Mi
      type: emptyDir
      mountPath: /usr/src/app/node_modules/i18n-iso-countries/langs
```
