### ISSUE TITLE
Error: Cannot find module './langs/br.json'

### ISSUE THREAD

**Issue by KrDw9ec4** [ZingLix/immich-geodata-cn#2]
我是在 immich-server 服务的 volumes 下添加挂载，在 .env 也给对应的环境变量赋值了。

```yaml
immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${GEODATA_LOCATION}:/build/geodata
      - ${I18N_ISO_LANG}:/usr/src/app/node_modules/i18n-iso-countries/langs
      - /etc/localtime:/etc/localtime:ro
...
```

但重新部署时遇到如下错误栈：

```
immich_server            | Detected CPU Cores: 4
immich_server            | node:internal/modules/cjs/loader:1252
immich_server            |   throw err;
immich_server            |   ^
immich_server            |
immich_server            | Error: Cannot find module './langs/br.json'
immich_server            | Require stack:
immich_server            | - /usr/src/app/node_modules/i18n-iso-countries/entry-node.js
immich_server            | - /usr/src/app/dist/repositories/map.repository.js
immich_server            | - /usr/src/app/dist/repositories/index.js
immich_server            | - /usr/src/app/dist/app.module.js
immich_server            | - /usr/src/app/dist/main.js
immich_server            |     at Function._resolveFilename (node:internal/modules/cjs/loader:1249:15)
immich_server            |     at Function._load (node:internal/modules/cjs/loader:1075:27)
immich_server            |     at TracingChannel.traceSync (node:diagnostics_channel:315:14)
immich_server            |     at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
immich_server            |     at Module.require (node:internal/modules/cjs/loader:1340:12)
immich_server            |     at require (node:internal/modules/helpers:141:16)
immich_server            |     at Object.<anonymous> (/usr/src/app/node_modules/i18n-iso-countries/entry-node.js:6:16)
immich_server            |     at Module._compile (node:internal/modules/cjs/loader:1546:14)
immich_server            |     at Object..js (node:internal/modules/cjs/loader:1689:10)
immich_server            |     at Module.load (node:internal/modules/cjs/loader:1318:32) {
immich_server            |   code: 'MODULE_NOT_FOUND',
immich_server            |   requireStack: [
immich_server            |     '/usr/src/app/node_modules/i18n-iso-countries/entry-node.js',
immich_server            |     '/usr/src/app/dist/repositories/map.repository.js',
immich_server            |     '/usr/src/app/dist/repositories/index.js',
immich_server            |     '/usr/src/app/dist/app.module.js',
immich_server            |     '/usr/src/app/dist/main.js'
immich_server            |   ]
immich_server            | }
immich_server            |
immich_server            | Node.js v22.11.0
```

导致 immich-server 一直启动不起来。
